<a href="https://colab.research.google.com/github/keshav5857/Machine-Learning/blob/main/ASSI3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1: Import Required Libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


Q2: Load Iris Dataset

In [ ]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"
cols = ['class','alcohol','malic_acid','ash','alcalinity','magnesium','phenols','flavanoids','nonflavanoid',
'proanthocyanins','color_intensity','hue','od280','proline']
df = pd.read_csv(url, names=cols)

Q3: Explore Dataset

In [ ]:
print(df.shape)
print(df['class'].unique())
df.describe()

(178, 14)
[1 2 3]


class     alcohol  malic_acid         ash  alcalinity   magnesium  \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean     1.938202   13.000618    2.336348    2.366517   19.494944   99.741573   
std      0.775035    0.811827    1.117146    0.274344    3.339564   14.282484   
min      1.000000   11.030000    0.740000    1.360000   10.600000   70.000000   
25%      1.000000   12.362500    1.602500    2.210000   17.200000   88.000000   
50%      2.000000   13.050000    1.865000    2.360000   19.500000   98.000000   
75%      3.000000   13.677500    3.082500    2.557500   21.500000  107.000000   
max      3.000000   14.830000    5.800000    3.230000   30.000000  162.000000   

          phenols  flavanoids  nonflavanoid  proanthocyanins  color_intensity  \
count  178.000000  178.000000    178.000000       178.000000       178.000000   
mean     2.295112    2.029270      0.361854         1.590899         5.058090   
std      0.625851    0.998859      0.124453         0.572359         2.318286   
min      0.980000    0.340000      0.130000         0.410000         1.280000   
25%      1.742500    1.205000      0.270000         1.250000         3.220000   
50%      2.355000    2.135000      0.340000         1.555000         4.690000   
75%      2.800000    2.875000      0.437500         1.950000         6.200000   
max      3.880000    5.080000      0.660000         3.580000        13.000000   

              hue       od280      proline  
count  178.000000  178.000000   178.000000  
mean     0.957449    2.611685   746.893258  
std      0.228572    0.709990   314.907474  
min      0.480000    1.270000   278.000000  
25%      0.782500    1.937500   500.500000  
50%      0.965000    2.780000   673.500000  
75%      1.120000    3.170000   985.000000  
max      1.710000    4.000000  1680.000000

Q4: Split Features (X) and Target (y)

In [ ]:
X = df.iloc[:,1:]
y = df['class']

Q5: Train‑Test Split (70:30)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

Q6: Build kNN Model (k = 3)

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

Q7: Make Predictions

In [ ]:
y_pred = knn.predict(X_test)


Q8: Show Correct and Wrong Predictions

In [ ]:
results = pd.DataFrame({'Actual': y_test.values, 'Predicted': y_pred})


Q9: Evaluate Model Performance

In [ ]:
print("Accuracy:", accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy: 0.7407407407407407
[[17  0  2]
 [ 1 15  5]
 [ 1  5  8]]
              precision    recall  f1-score   support

           1       0.89      0.89      0.89        19
           2       0.75      0.71      0.73        21
           3       0.53      0.57      0.55        14

    accuracy                           0.74        54
   macro avg       0.73      0.73      0.73        54
weighted avg       0.74      0.74      0.74        54



Conclusion:-
The kNN classifier predicts wine categories based on feature similarity. Accuracy depends on k
value and feature scaling. Misclassified samples occur where class boundaries overlap.
